name: Host Tests

on:
  push:
    branches: [ main, 'feature/**', 'bugfix/**', 'optimisation/**', 'work/**' ]
  pull_request:

jobs:
  host-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ESPressio-Web
      - name: Check out ESPressio System working branch
        uses: actions/checkout@v4
        with:
          repository: ESPressio-Development-Platform/ESPressio-System
          ref: main
          path: ESPressio-System
      - name: Check out ESPressio Observable working branch
        uses: actions/checkout@v4
        with:
          repository: ESPressio-Development-Platform/ESPressio-Observable
          ref: main
          path: ESPressio-Observable
      - name: Check out ESPressio Persistence working branch
        uses: actions/checkout@v4
        with:
          repository: ESPressio-Development-Platform/ESPressio-Persistence
          ref: main
          path: ESPressio-Persistence
      - name: Check out ESPressio State working branch
        uses: actions/checkout@v4
        with:
          repository: ESPressio-Development-Platform/ESPressio-State
          ref: main
          path: ESPressio-State
      - name: Check out ESPressio Event working branch
        uses: actions/checkout@v4
        with:
          repository: ESPressio-Development-Platform/ESPressio-Event
          ref: main
          path: ESPressio-Event
      - name: Check out ESPressio Command working branch
        uses: actions/checkout@v4
        with:
          repository: ESPressio-Development-Platform/ESPressio-Command
          ref: main
          path: ESPressio-Command
      - name: Check out ESPressio Threads working branch
        uses: actions/checkout@v4
        with:
          repository: ESPressio-Development-Platform/ESPressio-Threads
          ref: main
          path: ESPressio-Threads
      - name: Check out ESPressio Task working branch
        uses: actions/checkout@v4
        with:
          repository: ESPressio-Development-Platform/ESPressio-Task
          ref: main
          path: ESPressio-Task
      - name: Check out ESPressio Timing working branch
        uses: actions/checkout@v4
        with:
          repository: ESPressio-Development-Platform/ESPressio-Timing
          ref: main
          path: ESPressio-Timing
      - name: Check out ESPressio Units
        uses: actions/checkout@v4
        with:
          repository: ESPressio-Development-Platform/ESPressio-Units
          ref: main
          path: ESPressio-Units
      - name: Configure
        run: cmake -S ESPressio-Web/tests -B build/tests
      - name: Build
        run: cmake --build build/tests --parallel
      - name: Run
        run: ctest --test-dir build/tests --output-on-failure
